name: Build release files

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  # Create windows release file
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout master and submodules
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Get version number
      id: get_ver
      shell: bash
      run: |
        tp_ver=$(grep "VERSION" "./tinypedal/const.py" | sed 's/\"//g' | sed 's/VERSION = //g')
        echo "app_ver=$(echo $tp_ver)" >> $GITHUB_OUTPUT

    # Setup environment for Windows build
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
        architecture: "x64"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2exe

    - name: Build Windows executable
      run: |
        python freeze_py2exe.py -c

    # Create & upload Windows release file
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TinyPedal-${{ steps.get_ver.outputs.app_ver }}-windows
        path: ./dist/

  # Create linux release file
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master and submodules
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Get version number
      id: get_ver
      shell: bash
      run: |
        tp_ver=$(grep "VERSION" "./tinypedal/const.py" | sed 's/\"//g' | sed 's/VERSION = //g')
        echo "app_ver=$(echo $tp_ver)" >> $GITHUB_OUTPUT

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TinyPedal-${{ steps.get_ver.outputs.app_ver }}-linux
        path: |
          ./
          !.git
          !pyRfactor2SharedMemory/.git
