name: Build release files

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Build version"
        required: true
        type: string

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - name: Checkout master and submodules
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
        architecture: "x64"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2exe

    - name: Build executable
      run: |
        python freeze_py2exe.py -c

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TinyPedal-${{ github.event.inputs.version }}-windows
        path: ./dist/

  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master and submodules
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TinyPedal-${{ github.event.inputs.version }}-linux
        path: ./
