name: Build release files

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout master and submodules
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Get version number
      id: get_ver
      shell: bash
      run: |
        tp_ver=$(grep "VERSION" "./tinypedal/const.py" | sed 's/\"//g' | sed 's/VERSION = //g')
        echo "app_ver=$(echo $tp_ver)" >> $GITHUB_OUTPUT

    # Create & upload Linux release file
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TinyPedal-${{ steps.get_ver.outputs.app_ver }}-linux
        path: |
          ./
          !.git
          !pyRfactor2SharedMemory/.git
